queue:
  name: Hosted VS2017
  demands: msbuild

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore

    feedsToUse: config

    nugetConfigPath: Nuget.Config


- task: MSBuild@1
  displayName: 'Build solution ToDoLine.sln'
  inputs:
    solution: ToDoLine.sln

